### ISSUE TITLE
Getting LUA error with the new UI from Reddit

### ISSUE THREAD

**Issue by weevs320** [Kkthnx/KkthnxUI#1]
Message: Interface\AddOns\oUF_AbuRaid\kill.lua:7: attempt to index global 'CompactRaidFrameManager' (a nil value)
Time: 08/30/15 10:55:04
Count: 1
Stack: Interface\AddOns\oUF_AbuRaid\kill.lua:7: in main chunk

Locals: frameHider = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to index global 'CompactRaidFrameManager' (a nil value)"

**Comment by Kkthnx** [comment]
Very weird. can you do a clean install?

**Comment by weevs320** [comment]
I logged on a few other characters and it seems to have resolved.  Or at least I'm no longer getting the error message.  Great work btw

**Comment by Kkthnx** [comment]
what were you doing when this error came up?
