### ISSUE TITLE
Comments closed on WoWinterface page

### ISSUE THREAD

**Issue by Minniehajj** [Kkthnx/KkthnxUI#11]
Hi there! Your comments are closed on the WoW Interface page so we cannot ask questions there.  Thanks!
Also, your nameplates, are they just the default blizzard ones? If so, is there any way to just get auras to show up above them? I love the way everything looks, just those nameplates I'd like to tweak a bit. Thanks!

**Comment by Kkthnx** [comment]
I am unsure as to how I wanna appraoch the nameplates right now. If i even decide to do anything with them. For now I personally am using 

http://www.curse.com/addons/wow/tidy-plates
with
http://www.curse.com/addons/wow/tidy-plates-blizzardplates

**Comment by Minniehajj** [comment]
Hmm, okay, I was just curious.  Guess I'll try something similar! Could you
unlock comments on the WoWInterface page?

On Tue, Oct 13, 2015 at 3:15 PM, Kkthnx <notifications@github.com> wrote:

> I am unsure as to how I wanna appraoch the nameplates right now. If i even
> decide to do anything with them. For now I personally am using
>
> http://www.curse.com/addons/wow/tidy-plates
> with
> http://www.curse.com/addons/wow/tidy-plates-blizzardplates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kkthnx/KkthnxUI/issues/11#issuecomment-147819935>.
>



-- 
-Minhajul Hoq

**Comment by Kkthnx** [comment]
Comments are locked because it is hard to manage 3 different page sources of comments. WoWI is locked because I requested it. Nothing against any of you but it piles up after some time having to check all 3 pages daily. Curse, Github, WoWI and not to mention the Pms. So locking it was a decision to prevent having to run around.

**Comment by Minniehajj** [comment]
Ah I see, my mistake.  it would be a good thing to at least note that that
is why comments were closed, my friends and I are all using your UI (moving
from KaitUI and my own UI setup) because we like how it is fundamentally
the same as the original UI and we're all just leveling new toons now in
preparation for legion.

On Tue, Oct 13, 2015 at 3:32 PM, Kkthnx <notifications@github.com> wrote:

> Closed #11 <https://github.com/Kkthnx/KkthnxUI/issues/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kkthnx/KkthnxUI/issues/11#event-434432859>.
>



-- 
-Minhajul Hoq
