### ISSUE TITLE
Focus Issue

### ISSUE THREAD

**Issue by HolyAkiao** [Kkthnx/KkthnxUI#12]
Hi

Logged in tonight and realised that I have no focus option when right clicking anybodies portrait.
Even manually entering /setfocus does nothing. With no addons installed the option is there, with only your UI installed its gone

**Comment by Kkthnx** [comment]
Try Shift Clicking the frame.

**Comment by HolyAkiao** [comment]
yeah cheers. turns out i was being a moron, I'll take a second attempt at it now and ask, how do you set up a target of target frame. I've turned the option on in the blizzard options
