### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI#14]
Message: Interface\FrameXML\PaperDollFrame.lua:914: Usage: BreakUpLargeNumbers(number[, natural])
Time: Sun Jan  6 13:14:24 2019
Count: 1
Stack: Interface\FrameXML\PaperDollFrame.lua:914: Usage: BreakUpLargeNumbers(number[, natural])
[C]: ?
[C]: ?
Interface\FrameXML\PaperDollFrame.lua:914: in function `PaperDollFrame_SetAttackSpeed'
Interface\FrameXML\PaperDollFrame.lua:180: in function `updateFunc'
Interface\FrameXML\PaperDollFrame.lua:1869: in function `PaperDollFrame_UpdateStats'
Interface\FrameXML\PaperDollFrame.lua:1426: in function <Interface\FrameXML\PaperDollFrame.lua:1422>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2635: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:2480: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2348: in function <Interface\FrameXML\UIParent.lua:2344>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:3176: in function `ShowUIPanel'
Interface\FrameXML\CharacterFrame.lua:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals:

**Comment by Kkthnx** [comment]
I do not see any mention of my UI in this error though it might be related to the missing stats plugin? Will dig deeper.

**Comment by kitaro2003** [comment]
Resetting defaults KkthnxUI  helped solve the problem.
I will look for what setting KkthnxUI causes this error.

**Comment by kitaro2003** [comment]
KkthnxUI>Misk>Improved Stats!  - Causes an error

**Comment by Kkthnx** [comment]
As I thought! Will fix this. Thank you! <3

**Comment by Kkthnx** [comment]
Let me know if this is fixed. Try to reproduce it. Thank you.

**Comment by Kkthnx** [comment]
Gonna mark this resolved. I haven't seen the issue since my fix.
