### ISSUE TITLE
filger and chat

### ISSUE THREAD

**Issue by das2019** [Kkthnx/KkthnxUI#15]
Hello. I like you addon, very cool addon.
But i want to see Arms warrior spell <a href="https://www.wowhead.com/spell=7384/overpower#comments">Overpower</a> stacks at Filger, and display name who talk in blizzard voice chat if that's possible.
Thank you for your addon and sorry for my english.

**Comment by Kkthnx** [comment]
Going to give this a look this week or weekend. Thank you for the report. Will update here when I do something with this.

**Comment by das2019** [comment]
spell [Overpower](https://www.wowhead.com/spell=7384/overpower#comments) stacks at Filger is working thanks. 
Now wait fix the blizz voice chat.
And i find one more bug, i don't see ticks when i do readycheck at party.

**Comment by Kkthnx** [comment]
We believe we have this tracked down and fixed in our private repo. Thank you. When the next major release comes, make a new bug report if this happens.
