### ISSUE TITLE
FrameXML Action Button

### ISSUE THREAD

**Issue by SunshineKris216** [Kkthnx/KkthnxUI#16]
KkthnxUI 8.35

Date: 2019-01-30 05:05:04
ID: 1
Error occured in: AddOn: KkthnxUI
Count: 1
Message: Note: AddOn KkthnxUI attempted to call a protected function (MultiCastActionButton1:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\ActionButton.lua:383:
      ..\FrameXML\ActionButton.lua:342
   [C]: ?
   [C]: ActionButton_Update()
   ..\FrameXML\ActionButton.lua:338: ActionButton_UpdateAction()
   ..\FrameXML\ActionBarController.lua:145: ActionBarController_ResetToDefault()
   ..\FrameXML\ActionBarController.lua:134: ActionBarController_UpdateAll()
   ..\FrameXML\ZoneAbility.lua:78:
      ..\FrameXML\ZoneAbility.lua:31
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  WorldFlightMapLoader, v8.1.0.0
  AAPCore, v8.1046
  Ace3, v
  AchievementsReminder, v
  AllTheThings, v1.8.3
  Altoholic, vr190
  AskMrRobot, v72
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AutoRepair, v
  AzerothAutoPilot, v
  BadBoy, vv8.1.3
  BarrelsOEasy, v1.1.14
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BigWigs, vv130
  CamelSpotter, v1.4.6
  CollectMe, v2.10.1
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DFontChatSizes, v3.4
  EasyObliterate, v31
  EasyiLvl, v1.6.2
  EasyScrap, v19
  FishingBuddy, v1.9.26
  GarrisonOrderHallReport, v2.1.3
  GatherMate2, v1.43.5
  Grail, v099
  GrailAchievements, v011
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GTFO, v4.46.15
  HandyNotes, vv1.5.4
  HandyNotesAchievements, v0.4.22
  HandyNotesArgus, vv0.12
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.30
  HandyNotesDirections, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.45
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHallowsEnd, vv1.4.3
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionClassOrderHalls, vv1.30
  HandyNotesLegionInstanceWorldQuests, vv1.17
  HandyNotesLegionMagePortals, v1.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.6.1
  HandyNotesMoleMachine, v1.1.3
  HandyNotesSummerFestival, vv1.5
  HandyNotesSuramarShalAranTelemancy, vv1.20
  HandyNotesTimelessIsleChests, v1.21
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWarfrontTreasures, v1
  HandyNotesWellRead, v8.0.0.0
  HealBot, v8.1.0.1
  HealBotTips, v8.1.0.0
  Identity2, v4.0.1
  KkthnxUI, v8.35
  KkthnxUIConfig, v8.35
  LegionInvasionTimer, vv8.1.1
  MapCoords, v0.28
  Masque, v8.0.1
  MasterPlanA, vA
  MinimalArchaeology, v8.0.12.2
  NPCScan, v8.0.1.13
  OneBag3, vv3.10.1
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  OverachieverTrade, v1.0.5
  Pawn, v2.2.35
  PetBattleMaster, v8.0.0
  PetJournalEnhanced, v2.9.30
  QuestCompletist, v109.22
  Rarity, v1.0 (r682-release)
  RarityOptions, v
  Scrap, v13.13
  ScrapSpotlight, v13.13
  SilverDragon, vv4.0.13
  SilverDragonBattleForAzeroth, vv4.0.13
  SilverDragonBurningCrusade, vv4.0.13
  SilverDragonCataclysm, vv4.0.13
  SilverDragonLegion, vv4.0.13
  SilverDragonMists, vv4.0.13
  SilverDragonVanilla, vv4.0.13
  SilverDragonWarlords, vv4.0.13
  SilverDragonWrath, vv4.0.13
  SimpleObjectiveProgress, vr30
  Simulationcraft, v1.10.10
  SmexyMats, v8.1.0.2
  Stubby, v8.0.6161 (SwimmingSeadragon)
  SuperGuildInviteReborn, v8.0.0
  TheUndermineJournal, v5.4.20190129
  TransmogStats, v
  WeakAuras, v2.11.1
  Wholly, v070
  WIM, v573
  WorldBossTimers, v0.1
  WorldFlightMap, v8.1.0.0
  WorldQuestTab, v8.1.02
  WoWDBProfiler, v
  YouGotMail, v8.0.0.001
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=e7b)

**Comment by Kkthnx** [comment]
Run my UI only, then see if you get this.

**Comment by Kkthnx** [comment]
Hmm, this is a tough one. I wonder if this is related to my code for the extra action button. What class are you? Can you give me a status report? You can do this in-game with `/kstatus`

**Comment by SunshineKris216** [comment]
![wowscrnshot_020519_120207](https://user-images.githubusercontent.com/31464771/52290468-1cd5de00-293e-11e9-869a-83d6044c4ced.jpg)
 Then pops up the multi bar not working right Date: 2019-02-05 12:09:23
ID: 1
Error occured in: Global
Count: 1
Message: MultiBarRight:SetScale(): Scale must be > 0
Debug:
   [C]: ?
   [C]: SetScale()
   ..\FrameXML\MultiActionBars.lua:85: MultiActionBar_Update()
   ..\FrameXML\InterfaceOptionsPanels.lua:1184: InterfaceOptions_UpdateMultiActionBars()
   [string "*:OnLoad"]:4: setFunc()
   ..\FrameXML\InterfaceOptionsPanels.lua:1154:
      ..\FrameXML\InterfaceOptionsPanels.lua:1147
Locals:
(*temporary) = MultiBarRight {
 0 = <userdata>
 SetScale = <function> defined =[C]:-1
 slideOut = <unnamed> {
 }
}
(*temporary) = -0.165010

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  WorldFlightMapLoader, v8.1.0.0
  AAPCore, v8.1046
  Ace3, v
  AllTheThings, v1.8.3
  Altoholic, vr190
  AskMrRobot, v72
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AutoRepair, v
  BadBoy, vv8.1.3
  BarrelsOEasy, v1.1.14
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BigWigs, vv133
  CamelSpotter, v1.4.6
  CollectMe, v2.10.1
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DFontChatSizes, v3.4
  EasyObliterate, v31
  EasyiLvl, v1.6.2
  EasyScrap, v19
  FishingBuddy, v1.9.26a1
  GarrisonOrderHallReport, v2.1.3
  GatherMate2, v1.43.5
  Grail, v099
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GTFO, v4.46.17
  HandyNotes, vv1.5.4
  HandyNotesAchievements, v0.4.22
  HandyNotesArgus, vv0.12
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.30
  HandyNotesDirections, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.45
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHallowsEnd, vv1.4.3
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionClassOrderHalls, vv1.30
  HandyNotesLegionInstanceWorldQuests, vv1.17
  HandyNotesLegionMagePortals, v1.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.6.1
  HandyNotesMoleMachine, v1.1.3
  HandyNotesSummerFestival, vv1.5
  HandyNotesSuramarShalAranTelemancy, vv1.20
  HandyNotesTimelessIsleChests, v1.21
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWarfrontTreasures, v1
  HandyNotesWellRead, v8.0.0.0
  HealBot, v8.1.0.1
  Identity2, v4.0.1
  KkthnxUI, v8.35
  KkthnxUIConfig, v8.35
  LegionInvasionTimer, vv8.1.1
  MapCoords, v0.28
  MasterPlanA, vA
  MinimalArchaeology, v8.0.12.2
  NPCScan, v8.0.1.13
  OneBag3, vv3.10.1
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  Pawn, v2.2.35
  PetBattleMaster, v8.0.0
  PetJournalEnhanced, v2.9.30
  QuestCompletist, v109.22
  Rarity, v1.0 (r683-release)
  RarityOptions, v
  Scrap, v13.13
  ScrapSpotlight, v13.13
  SilverDragon, vv4.0.13
  SilverDragonBattleForAzeroth, vv4.0.13
  SilverDragonBurningCrusade, vv4.0.13
  SilverDragonCataclysm, vv4.0.13
  SilverDragonLegion, vv4.0.13
  SilverDragonMists, vv4.0.13
  SilverDragonVanilla, vv4.0.13
  SilverDragonWarlords, vv4.0.13
  SilverDragonWrath, vv4.0.13
  SimpleObjectiveProgress, vr30
  Simulationcraft, v1.10.10
  SmexyMats, v8.1.0.2
  Stubby, v8.0.6161 (SwimmingSeadragon)
  SuperGuildInviteReborn, v8.0.0
  TheUndermineJournal, v5.4.20190202
  TransmogStats, v
  WeakAuras, v2.11.3
  Wholly, v070
  WorldBossTimers, v0.1
  WorldFlightMap, v8.1.0.0
  WorldQuestTab, v8.1.02
  WoWDBProfiler, v
  YouGotMail, v8.0.0.001
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=de2)

**Comment by Kkthnx** [comment]
I already fixed the MultiBarRight:SetScale(): Scale must be > 0, I just have yet to push it to Curse. I'm going to try to reproduce this tonight when I am home.

Also, with you having so many other AddOns active it is hard to really determine if this is my UI causing this or not. I will look into it and debug it tonight though. Thanks again for more info.

**Comment by Kkthnx** [comment]
We believe we have this tracked down and fixed in our private repo. Thank you. When the next major release comes, make a new bug report if this happens.
