### ISSUE TITLE
addon image

### ISSUE THREAD

**Issue by felipe1557** [Kkthnx/KkthnxUI#17]
I wonder how to make my interface as the image below as installed but there was only the default raid blizz and these icons alliance and horde were different
![8b2f9938-57f8-11e5-84bd-4e7311f248a6](https://cloud.githubusercontent.com/assets/16226440/11688685/340184f0-9e75-11e5-923b-aa37de4bbb84.jpg)

**Comment by Kkthnx** [comment]
This is because I was using oUF_Abu / oUF_AbuRaid
