### ISSUE TITLE
Action bar bug

### ISSUE THREAD

**Issue by Drastaro** [Kkthnx/KkthnxUI#17]
**Description**
There is an action bug bar on High Tinker boss.

**Version Number**
8.35

**Steps to Reproduce**
When you jump in the robot (when shrunk) the first time the action bar is always bugged and does not display the robots actions.

**Expected Behavior**
Should show robots action instead of the users.

**Actual Behavior**
It shows my action bar/spells instead of the robots

**Comment by Kkthnx** [comment]
We believe we have this tracked down and fixed in our private repo. Thank you. When the next major release comes, make a new bug report if this happens.
