### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by Purpleblack** [Kkthnx/KkthnxUI#2]
Bugs:
1) Cant change Data Bars Azerite color
2) Toggle Border color not changing all frames (ToT frame)
--
--
Please consider these changes:
1) option to adjust scale of UnitFrames
2) option to hide (or fade) the chat buttons (top right) Functions and Options Menu

**Comment by Kkthnx** [comment]
Accepted. Though I will think about 3

**Comment by Kkthnx** [comment]
Fixed, though I will not add suggestion 3

https://github.com/Kkthnx/KkthnxUI/commit/5044cf7dce0cdda7c83fddeb973dff6d3fa8c42f
