### ISSUE TITLE
ADDON failure box when 2 different tasks are performed

### ISSUE THREAD

**Issue by Nymike58** [Kkthnx/KkthnxUI#25]
**Description**
Can not create a group or party or when I am rezzed the box comes up ADDON failure

**Version Number**

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**
NO ADDON failure box

**Actual Behavior**
FAILURE ADDON shows up in a big box on the screen

**Only KkthnxUI Enabled**

**Additional Information**
none

**Error Log**
Dont know hoe to add one

```

```

**Comment by Nymike58** [comment]
![wowscrnshot_022219_210517](https://user-images.githubusercontent.com/47833527/53683236-7aa2df00-3ccc-11e9-8041-19737c9aa551.jpg)

**Comment by Nymike58** [comment]
Constant this error is when rezzed

**Comment by Nymike58** [comment]
![wowscrnshot_022719_230058](https://user-images.githubusercontent.com/47833527/53683262-aaea7d80-3ccc-11e9-826c-1930d23b3072.jpg)

**Comment by Kkthnx** [comment]
Added to be fixed before the next release, thank you.

**Comment by Kkthnx** [comment]
We believe we have this tracked down and fixed in our private repo. Thank you. When the next major release comes, make a new bug report if this happens.

**Comment by Nymike58** [comment]
> We believe we have this tracked down and fixed in our private repo. Thank you. When the next major release comes, make a new bug report if this happens.

Sorry for my ignorance but how do i fix this now? I download all addons through Twitch. Are you saying to just download it again? or wait till next patch? What is Private Repo?
