### ISSUE TITLE
error MiniMap.lua:207

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI#3]
When hovering over the mini map. v 8.13

16x KkthnxUI\Modules\Maps\MiniMap.lua:207: attempt to index field 'PerformanceFrame' (a nil value)
KkthnxUI\Modules\Maps\MiniMap.lua:207: in function <KkthnxUI\Modules\Maps\MiniMap.lua:206>
[C]: ?

Locals:
self = Minimap {
 0 = <userdata>
 Backgrounds = <unnamed> {
 }
 location = <unnamed> {
 }
 SetBorderColor = <function> defined @KkthnxUI\Core\Border.lua:31
 HideBorder = <function> defined @KkthnxUI\Core\Border.lua:72
 GetBackdropBorderColor = <function> defined @KkthnxUI\Core\Border.lua:57
 Borders = <function> defined @KkthnxUI\Core\Border.lua:92
 GetBorderColor = <function> defined @KkthnxUI\Core\Border.lua:57
 timer = 0
 SetBackdropBorderColor = <function> defined @KkthnxUI\Core\Border.lua:31
 ShowBorder = <function> defined @KkthnxUI\Core\Border.lua:64
 SetZoom = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'PerformanceFrame' (a nil value)"
K = <table> {
 GetScreenQuadrant = <function> defined @KkthnxUI\Core\Functions.lua:336
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:496
 LoadSkadaProfile = <function> defined @KkthnxUI\Config\AddOnData\Skada.lua:9
 LoadPawnProfile = <function> defined @KkthnxUI\Config\AddOnData\Pawn.lua:9
 GetAnchors = <function> defined @KkthnxUI\Core\Functions.lua:209
 modules = <table> {
 }
 Race = "Scourge"
 MapInfo_CoordsStopWatching = <function> defined @KkthnxUI\Core\MapInfo.lua:51
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:122
 StaticPopup_EscapePressed = <function> defined @KkthnxUI\Core\StaticPopups.lua:232
 TextureTable = <table> {
 }
 FixGFXEngine = <function> defined @KkthnxUI\Core\Commands.lua:291
 SetDefaultModulePrototype = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 DispelClasses = <table> {
 }
 SetUIScale = <function> defined @KkthnxUI\Core\Commands.lua:328
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ScheduleTimer = <function> defined @HHTD\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 PetBarUpdate = <function> defined @KkthnxUI\Modules\Actionbars\Core.lua:184
 PriestColors = <table> {
 }
 GetFont = <function> defined @KkthnxUI\Core\Media.lua:45
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 Class = "ROGUE"
 EnableBlizzardAddOns = <function> defined @KkthnxUI\Core\Commands.lua:536
 ShortValue = <function> defined @KkthnxUI\Core\Functions.lua:87
 KillMenuOption = <function> defined @KkthnxUI\Core\Functions.lua:384
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:219
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 KeyBindFrame = <function> defined @KkthnxUI\Core\Commands.lua:274
 Spec = 0
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:224
 GMTicket = <function> defined @KkthnxUI\Core\Commands.lua:268
 Version = "8.13"
 Noop = <function> defined @KkthnxUI\Init.lua:81
 WowPatch = "8.0.1"
 GetFormattedText = <function> defined @KkthnxUI\Core\Functions.lua:304
 Media = KkthnxUIFonts {
 }
 OnInitialize = <function> defined @KkthnxUI\Init.lua:107
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 StaticPopup_EditBoxOnEscapePressed = <function> defined @KkthnxUI\Core\StaticPopups.lua:441
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:163
 Client = "ruRU"
 optionsFrame = <unnamed> {
 }
 GetPlayerMapPos = <function> defined @KkthnxUI\Core\MapInfo.

**Comment by Kkthnx** [comment]
Will be fixed tomorrow. I forgot to add checks.

**Comment by Kkthnx** [comment]
Fixed https://github.com/Kkthnx/KkthnxUI/commit/5044cf7dce0cdda7c83fddeb973dff6d3fa8c42f
