### ISSUE TITLE
Kill.lua github version

### ISSUE THREAD

**Issue by kitaro2003** [Kkthnx/KkthnxUI#38]
28x KkthnxUI\Core\Kill.lua:60: attempt to index field 'Scaling' (a nil value)
KkthnxUI\Core\Kill.lua:60: in function <KkthnxUI\Core\Kill.lua:11>

Locals:
UIHider = UIFrameHider {
 0 = <userdata>
 children = <table> {
 }
}
(*temporary) = nil
(*temporary) = PartyMemberBackground {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = <function> defined @KkthnxUI\Core\Functions.lua:374
(*temporary) = "attempt to index field 'Scaling' (a nil value)"
K = <table> {
 GetScreenQuadrant = <function> defined @KkthnxUI\Core\Functions.lua:306
 GetTimeInfo = <function> defined @KkthnxUI\Core\Functions.lua:470
 LoadSkadaProfile = <function> defined @KkthnxUI\Config\AddOnData\Skada.lua:9
 LoadPawnProfile = <function> defined @KkthnxUI\Config\AddOnData\Pawn.lua:9
 GetAnchors = <function> defined @KkthnxUI\Core\Functions.lua:179
 modules = <table> {
 }
 Race = "Scourge"
 MapInfo_CoordsStopWatching = <function> defined @KkthnxUI\Core\MapInfo.lua:51
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 UIFrameFade_OnUpdate = <function> defined @KkthnxUI\Core\Animation.lua:124
 StaticPopup_EscapePressed = <function> defined @KkthnxUI\Core\StaticPopups.lua:373
 TextureTable = <table> {
 }
 FixGFXEngine = <function> defined @KkthnxUI\Core\Commands.lua:395
 SetDefaultModulePrototype = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 SetUIScale = <function> defined @KkthnxUI\Core\Commands.lua:431
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @HHTD\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 PetBarUpdate = <function> defined @KkthnxUI\Modules\Actionbars\Core.lua:165
 PriestColors = <table> {
 }
 GetFont = <function> defined @KkthnxUI\Core\Media.lua:67
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 Class = "ROGUE"
 EnableBlizzardAddOns = <function> defined @KkthnxUI\Core\Commands.lua:639
 hooks = <table> {
 }
 UIScale = 0.711111
 KillMenuOption = <function> defined @KkthnxUI\Core\Functions.lua:354
 ShortenString = <function> defined @KkthnxUI\Core\Functions.lua:189
 Credits = "Alza, Azilroka, Blazeflack, Caellian, Caith, Darth Predator, Elv, Goldpaw, Haleth, Haste, Hungtar, Hydra, Ishtara, KkthnxUI_Community, LightSpark, Magicnachos, Merathilis, Nightcracker, P3lim, Rav99, Roth, Shestak, Simpy, Sticklord, Tekkub, Tohveli, Tukz, Tulla, Tuller, oUF_Team"
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 KeyBindFrame = <function> defined @KkthnxUI\Core\Commands.lua:378
 Spec = 0
 tDeleteItem = <function> defined @KkthnxUI\Core\Animation.lua:229
 GMTicket = <function> defined @KkthnxUI\Core\Commands.lua:337
 Version = "8.38"
 Noop = <function> defined @KkthnxUI\Init.lua:82
 WowPatch = "8.1.5"
 GetFormattedText = <function> defined @KkthnxUI\Core\Functions.lua:274
 StaticPopupFrames = <table> {
 }
 Media = KkthnxUIFonts {
 }
 OnInitialize = <function> defined @KkthnxUI\Init.lua:115
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 ScanTooltipTextures = <function> defined @KkthnxUI\Init.lua:155
 StaticPopup_EditBoxOnEscapePressed = <function> defined @KkthnxUI\Core\StaticPopups.lua:582
 GUID = "Player-1615-085FB96A"
 baseName = "KkthnxUI"
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UIFrameFade = <function> defined @KkthnxUI\Core\Animation.lua:165
 RawHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:313
 Client = "ruRU"

**Comment by Kkthnx** [comment]
Fix with commit https://github.com/Kkthnx/KkthnxUI/commit/68df69a82dd0c77a5539c212d0b18a06c38e644e

Thank you for the report.
