### ISSUE TITLE
Pet unitframe bug when using vehicle

### ISSUE THREAD

**Issue by solumg** [Kkthnx/KkthnxUI#4]
This is a bug in from abu(did report to him but he quit). When leaving vehicle the pet frame does not update and is still showing as if its a player unitframe.
Here is a shot:
![untitled](https://cloud.githubusercontent.com/assets/6905530/9575039/c17741b4-4fcc-11e5-916c-eb1335fee53d.png)

**Comment by Kkthnx** [comment]
Fixed https://github.com/Kkthnx/KkthnxUI/commit/3a9d324b58d300dbffef33e5e315770233e9c048

You can thank sicklord
