### ISSUE TITLE
Scaling options

### ISSUE THREAD

**Issue by solumg** [Kkthnx/KkthnxUI#6]
This is more of a feature request. I often play at a 15" mac and having UIscaling off makes everything microscopic and very hard to see. Maybe have a options for scaling things?

**Comment by Kkthnx** [comment]
Err, I forgot to add the scaling back in. I have been working on new borders and stuff and meant to turn the scaling back on.

**Comment by Kkthnx** [comment]
Are you talking about individual stuff or just the options in the interface?

**Comment by solumg** [comment]
I meant the interface option. However it was a pointless request. Can just edit config files. Ignore this 'issue' :P

**Comment by Kkthnx** [comment]
I was re-enabled awhile back 
https://github.com/Kkthnx/KkthnxUI/commit/0c1262162fc101527d8cc2b08c7ee29691ad2bf0

**Comment by Kkthnx** [comment]
![dq8xrsr](https://cloud.githubusercontent.com/assets/1692977/9698365/9974aaa0-5380-11e5-8aae-b37b50ca7242.jpg)

This is still very early WIP. This was taken about 5 hours ago from this post as of right now I am most of it done and will release the first pass on the new in-game config and file system / engine by sunday night.
