### ISSUE TITLE
KkthnxUI affects Rarity addon minimap icon tooltip

### ISSUE THREAD

**Issue by akshun** [Kkthnx/KkthnxUI#7]
**Description**
Rarity addon tool-tip on minimap icon background texture missing/transparent/replaced

**Version Number**
8.28-release

**Steps to Reproduce**
1. Have KkthnxUI installed/enabled
2. Have Rarity installed/enabled

**Expected Behavior**
Tooltip background for Rarity icon should be unaffected.

**Actual Behavior**
Becomes transparent or missing.

**Only KkthnxUI Enabled**
KkthnxUI and Rarity enabled only: https://pasteboard.co/HGcwi7w.jpg
KkthnxUI disabled - every other addon enabled: https://pasteboard.co/HGcwRgt.jpg
Details tooltip with KkthnxUI, Rarity and Details only: https://pasteboard.co/HGcyHNcR.jpg
Addons: https://pasteboard.co/HGcxciA.png

**Additional Information**
Is not a new issue. But I figured I should do the proper thing and alert you. 
I have used Kkthnx for a few months, its amazing - I have had this tooltip bug since first use.
I cannot locate in Rarity anything to set its tooltip texture from the addon config menu.

**Error Log**
No errors I have caught or noticed. I assume something like a similar texture is shared between the two addons and thus Kkthnx overrides it and affects the tooltip
```

```

**Comment by Kkthnx** [comment]
Very interesting. Will have a look into this.

**Comment by akshun** [comment]
Tooltip looks good in Git version I loaded just then.
Thank you!
