### ISSUE TITLE
Stats bugging

### ISSUE THREAD

**Issue by Syyck** [Kkthnx/KkthnxUI#9]
Hey,

when I want to setup the stats, I have to activate "contacts" to see the other stats. As long as its deactivated it only shows the clock and fps/mem/latency

**Comment by Kkthnx** [comment]
I will look into this issue this weekend.

**Comment by Kkthnx** [comment]
Try something for me. Esc > KkthnxUI or do /cfg in chat then go down to top panel and enable it. Let me know if this fixes it.

**Comment by Syyck** [comment]
No, doesnt work. Its not that important for me to not see the contact stat, but I thought I should report it. Maybe others have this bug too.

**Comment by Kkthnx** [comment]
Well it is an issue on my end I do believe I will get working on it later today.

**Comment by Syyck** [comment]
Dont rush man! I love this UI tho :)
